#############################################################################
# Makefile for building aucredit
# Generated by tmake at 12:54, 2004/02/22
#     Project: aucrEdit
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	arm-linux-gcc
CXX	=	arm-linux-g++
CFLAGS	=	-pipe -Wall -W -O2 -DNO_DEBUG
CXXFLAGS=	-pipe -DQT_QWS_EBX -DQT_QWS_CUSTOM -DQWS -fno-exceptions -fno-rtti -Wall -W -O2 -DNO_DEBUG
INCPATH	=	-I$(QPEDIR)/include -I$(QTDIR)/include
LINK	=	arm-linux-gcc
LFLAGS	=	
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -lqpe -lqte
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	aucrEdit.h \
		alfEdit.h \
		textEdit.h \
		editArea.h \
		recogArea.h \
		AUCR.h
SOURCES =	aucrEdit.cpp \
		alfEdit.cpp \
		textEdit.cpp \
		editArea.cpp \
		recogArea.cpp \
		AUCR.c
OBJECTS =	aucrEdit.o \
		alfEdit.o \
		textEdit.o \
		editArea.o \
		recogArea.o \
		AUCR.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	moc_aucrEdit.cpp \
		moc_alfEdit.cpp \
		moc_textEdit.cpp \
		moc_editArea.cpp \
		moc_recogArea.cpp
OBJMOC	=	moc_aucrEdit.o \
		moc_alfEdit.o \
		moc_textEdit.o \
		moc_editArea.o \
		moc_recogArea.o
DIST	=	
TARGET	=	aucredit
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: Makefile

Makefile: aucrEdit.pro
	tmake aucrEdit.pro -o Makefile

dist:
	$(TAR) aucrEdit.tar aucrEdit.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) aucrEdit.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

aucrEdit.o: aucrEdit.cpp \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		AUCR.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		editArea.h \
		/opt/Qtopia/sharp/include/qaccel.h

alfEdit.o: alfEdit.cpp \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		AUCR.h \
		editArea.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h

textEdit.o: textEdit.cpp \
		textEdit.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		AUCR.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		editArea.h

editArea.o: editArea.cpp \
		editArea.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		AUCR.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h

recogArea.o: recogArea.cpp \
		recogArea.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		AUCR.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		editArea.h

AUCR.o: AUCR.c \
		AUCR.h

moc_aucrEdit.o: moc_aucrEdit.cpp \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		AUCR.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		aucrEdit.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		editArea.h

moc_alfEdit.o: moc_alfEdit.cpp \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		AUCR.h \
		editArea.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		alfEdit.h

moc_textEdit.o: moc_textEdit.cpp \
		textEdit.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		AUCR.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		textEdit.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		editArea.h

moc_editArea.o: moc_editArea.cpp \
		editArea.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		AUCR.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		editArea.h

moc_recogArea.o: moc_recogArea.cpp \
		recogArea.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qpainter.h \
		/opt/Qtopia/sharp/include/qpen.h \
		/opt/Qtopia/sharp/include/qpointarray.h \
		/opt/Qtopia/sharp/include/qwmatrix.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		AUCR.h \
		aucrEdit.h \
		/opt/Qtopia/sharp/include/qmainwindow.h \
		/opt/Qtopia/sharp/include/qwidgetstack.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qptrdict.h \
		/opt/Qtopia/sharp/include/qmenubar.h \
		/opt/Qtopia/sharp/include/qpopupmenu.h \
		/opt/Qtopia/sharp/include/qmenudata.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qsignal.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qlayout.h \
		/opt/Qtopia/sharp/include/qabstractlayout.h \
		/opt/Qtopia/sharp/include/qdialog.h \
		/opt/Qtopia/sharp/include/qtooltip.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qmessagebox.h \
		/opt/Qtopia/sharp/include/qclipboard.h \
		/opt/Qtopia/sharp/include/qhbox.h \
		/opt/Qtopia/sharp/include/qpe/applnk.h \
		/opt/Qtopia/sharp/include/qdict.h \
		/opt/Qtopia/sharp/include/qpe/fileselector.h \
		/opt/Qtopia/sharp/include/qvbox.h \
		/opt/Qtopia/sharp/include/qtoolbutton.h \
		/opt/Qtopia/sharp/include/qlistview.h \
		/opt/Qtopia/sharp/include/qscrollview.h \
		/opt/Qtopia/sharp/include/qscrollbar.h \
		/opt/Qtopia/sharp/include/qrangecontrol.h \
		/opt/Qtopia/sharp/include/qdrawutil.h \
		/opt/Qtopia/sharp/include/qpe/global.h \
		/opt/Qtopia/sharp/include/qguardedptr.h \
		/opt/Qtopia/sharp/include/qpe/config.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qpe/filemanager.h \
		textEdit.h \
		/opt/Qtopia/sharp/include/qmultilineedit.h \
		/opt/Qtopia/sharp/include/qtableview.h \
		recogArea.h \
		alfEdit.h \
		/opt/Qtopia/sharp/include/qbuttongroup.h \
		/opt/Qtopia/sharp/include/qgroupbox.h \
		editArea.h

moc_aucrEdit.cpp: aucrEdit.h
	$(MOC) aucrEdit.h -o moc_aucrEdit.cpp

moc_alfEdit.cpp: alfEdit.h
	$(MOC) alfEdit.h -o moc_alfEdit.cpp

moc_textEdit.cpp: textEdit.h
	$(MOC) textEdit.h -o moc_textEdit.cpp

moc_editArea.cpp: editArea.h
	$(MOC) editArea.h -o moc_editArea.cpp

moc_recogArea.cpp: recogArea.h
	$(MOC) recogArea.h -o moc_recogArea.cpp

